#ifndef FTOPTION_H_
#define FTOPTION_H_

#include <ft2build.h>

FT_BEGIN_HEADER

/* stream support is required for font table parsing (seek between tables) */
/* #define FT_CONFIG_OPTION_DISABLE_STREAM_SUPPORT */

#define TT_CONFIG_OPTION_BYTECODE_INTERPRETER

#define TT_CONFIG_CMAP_FORMAT_0
#define TT_CONFIG_CMAP_FORMAT_2
#define TT_CONFIG_CMAP_FORMAT_4
#define TT_CONFIG_CMAP_FORMAT_6
#define TT_CONFIG_CMAP_FORMAT_8
#define TT_CONFIG_CMAP_FORMAT_10
#define TT_CONFIG_CMAP_FORMAT_12
#define TT_CONFIG_CMAP_FORMAT_13
#define TT_CONFIG_CMAP_FORMAT_14

#undef FT_CONFIG_OPTION_USE_LZW
#undef FT_CONFIG_OPTION_USE_ZLIB
#undef FT_CONFIG_OPTION_USE_BZIP2
#undef FT_CONFIG_OPTION_USE_PNG
#undef FT_CONFIG_OPTION_USE_HARFBUZZ
#undef FT_CONFIG_OPTION_USE_BROTLI

#undef FT_CONFIG_OPTION_ENVIRONMENT_PROPERTIES
#undef FT_CONFIG_OPTION_POSTSCRIPT_NAMES
#undef FT_CONFIG_OPTION_ADOBE_GLYPH_LIST
#undef FT_CONFIG_OPTION_SUBPIXEL_RENDERING
#undef FT_CONFIG_OPTION_ERROR_STRINGS

#undef TT_CONFIG_OPTION_GX_VAR_SUPPORT
#undef TT_CONFIG_OPTION_BDF
#undef TT_CONFIG_OPTION_GPOS_KERNING

#undef FT_CONFIG_OPTION_SVG

#define FT_MAX_MODULES  32
#define T1_MAX_DICT_DEPTH  5
#define T1_MAX_SUBRS_CALLS  16
#define T1_MAX_CHARSTRINGS_OPERANDS  256

FT_END_HEADER

#endif
