/* Override GLib platform detection for OpenHobbyOS */
#ifdef G_CREDENTIALS_USE_LINUX_UCRED
#undef G_CREDENTIALS_USE_LINUX_UCRED
#define G_CREDENTIALS_USE_LINUX_UCRED 0
#endif

#ifdef G_CREDENTIALS_SOCKET_GET_CREDENTIALS_SUPPORTED
#undef G_CREDENTIALS_SOCKET_GET_CREDENTIALS_SUPPORTED
#endif

#ifdef G_CREDENTIALS_UNIX_CREDENTIALS_MESSAGE_SUPPORTED
#undef G_CREDENTIALS_UNIX_CREDENTIALS_MESSAGE_SUPPORTED
#endif

#ifdef G_CREDENTIALS_SPOOFING_SUPPORTED
#undef G_CREDENTIALS_SPOOFING_SUPPORTED
#endif

#ifdef G_CREDENTIALS_SUPPORTED
#undef G_CREDENTIALS_SUPPORTED
#endif
